/**
 * Product classification — reflects the OEM / trading split confirmed by
 * Kabir Panchal on 2026-09-30 (see docs/business-profile.md §2b).
 *
 *   oem       — manufactured in-house at the Ahmedabad plant.
 *   trading   — distributed only; sourced from partners.
 *   ambiguous — mix of in-house and partner supply (SKU-specific).
 */
export type ProductClassification = 'oem' | 'trading' | 'ambiguous';

export interface ProductCategory {
  slug: string;
  path: string;
  name: string;
  shortDescription: string;
  classification: ProductClassification;
  verifiedAt?: string;
  /**
   * Public image path. Currently points at a grey-card SVG placeholder
   * written to disk with a `.jpg` extension (generated by
   * `scripts/generate-placeholders.mjs`). When a real .jpg lands at the
   * same path, it silently replaces the placeholder — no code change
   * needed. Filenames mirror the manifest in `product-images/` (the
   * research-reference folder, gitignored) so swapping stays trivial.
   */
  image: string;
  imageAlt: string;
}

export const productCategories: ProductCategory[] = [
  {
    slug: 'foundation-bolts',
    path: '/products/foundation-bolts/',
    name: 'Foundation Bolts',
    shortDescription:
      'J-, L-, U-type and hooked foundation / anchor bolts for civil and industrial anchoring.',
    classification: 'oem',
    image: '/images/products/bolts/j-bolt.jpg',
    imageAlt: 'KP Fasteners foundation bolt — representative image (photo pending)',
  },
  {
    slug: 'stud-bolts',
    path: '/products/stud-bolts/',
    name: 'Stud Bolts',
    shortDescription: 'Metric and imperial stud bolts for flange and structural applications.',
    classification: 'oem',
    image: '/images/products/threaded-rods/threaded-rod-stud.jpg',
    imageAlt: 'KP Fasteners stud bolt — representative image (photo pending)',
  },
  {
    slug: 'sag-rods',
    path: '/products/sag-rods/',
    name: 'Sag Rods',
    shortDescription:
      'Threaded sag rods for PEB purlin bracing, structural steel, and solar racking cross-bracing.',
    classification: 'oem',
    image: '/images/products/threaded-rods/threaded-rod-stud.jpg',
    imageAlt: 'KP Fasteners threaded sag rod — representative image (photo pending)',
  },
  {
    slug: 'scaffold-accessories',
    path: '/products/scaffold-accessories/',
    name: 'Scaffold Accessories',
    shortDescription:
      'Scaffolding fastener accessories — manufactured and supplied, SKU-specific.',
    classification: 'ambiguous',
    image: '/images/products/threaded-rods/wedge-anchor.jpg',
    imageAlt: 'Scaffold accessory — representative image (photo pending)',
  },
  {
    slug: 'hex-bolts-nuts',
    path: '/products/hex-bolts-nuts/',
    name: 'Hex Bolts & Nuts',
    shortDescription:
      'Hex head bolts and hex nuts across metric and imperial standards — distribution range.',
    classification: 'trading',
    image: '/images/products/bolts/hex-bolt-hex-nut.jpg',
    imageAlt: 'Hex bolt and hex nut — representative image (photo pending)',
  },
  {
    slug: 'csk-allen-bolts',
    path: '/products/csk-allen-bolts/',
    name: 'CSK Allen Bolts',
    shortDescription:
      'Countersunk socket-head cap screws — distribution range across grades and finishes.',
    classification: 'trading',
    image: '/images/products/bolts/allen-socket-csk-screw.jpg',
    imageAlt: 'Countersunk Allen socket screw — representative image (photo pending)',
  },
  {
    slug: 'tie-rods',
    path: '/products/tie-rods/',
    name: 'Tie Rods',
    shortDescription:
      'Threaded tie rods and turnbuckle assemblies — distribution range.',
    classification: 'trading',
    image: '/images/products/threaded-rods/threaded-rod-stud.jpg',
    imageAlt: 'Tie rod — representative image (photo pending)',
  },
  {
    slug: 'solar-accessories',
    path: '/products/solar-accessories/',
    name: 'Solar Accessories',
    shortDescription:
      'MMS bolts, T-head bolts, hanger bolts, module clamps — distribution range.',
    classification: 'trading',
    image: '/images/products/bolts/hex-flange-bolt.jpg',
    imageAlt: 'Solar mounting accessory — representative image (photo pending)',
  },
  {
    slug: 'custom-fasteners',
    path: '/products/custom-fasteners/',
    name: 'Custom Fasteners',
    shortDescription:
      'Drawing-based sourcing for non-standard fasteners — distribution / partner-supply.',
    classification: 'trading',
    image: '/images/products/bolts/socket-head-cap-screw.jpg',
    imageAlt: 'Socket-head cap screw — representative image (photo pending)',
  },
];

export function findProduct(slug: string): ProductCategory | undefined {
  return productCategories.find((p) => p.slug === slug);
}
