/**
 * Product classification — reflects the OEM / trading split confirmed by
 * Kabir Panchal on 2026-09-30 (see docs/business-profile.md §2b).
 *
 *   oem       — manufactured in-house at the Ahmedabad plant.
 *   trading   — distributed only; sourced from partners.
 *   ambiguous — mix of in-house and partner supply (SKU-specific).
 */
export type ProductClassification = 'oem' | 'trading' | 'ambiguous';

export interface ProductCategory {
  slug: string;
  path: string;
  name: string;
  shortDescription: string;
  classification: ProductClassification;
  verifiedAt?: string;
  /**
   * Public image path. Currently points at a grey-card SVG placeholder
   * written to disk with a `.jpg` extension (generated by
   * `scripts/generate-placeholders.mjs`). When a real .jpg lands at the
   * same path, it silently replaces the placeholder — no code change
   * needed. Filenames mirror the manifest in `product-images/` (the
   * research-reference folder, gitignored) so swapping stays trivial.
   */
  image: string;
  imageAlt: string;
}

export const productCategories: ProductCategory[] = [
  {
    slug: 'foundation-bolts',
    path: '/products/foundation-bolts/',
    name: 'Foundation Bolts',
    shortDescription:
      'J-, L-, U-type and hooked foundation / anchor bolts for civil and industrial anchoring.',
    classification: 'oem',
    image: '/images/products/bolts/foundation-anchor-bolts.webp',
    imageAlt: 'KP Fasteners foundation bolts — J, L, U and mechanical anchor bolts to IS 5624 and ASTM F1554',
  },
  {
    slug: 'stud-bolts',
    path: '/products/stud-bolts/',
    name: 'Stud Bolts',
    shortDescription: 'Metric and imperial stud bolts for flange and structural applications.',
    classification: 'oem',
    image: '/images/products/threaded-rods/threaded-rod-stud.webp',
    imageAlt: 'KP Fasteners ASTM A193 B7 stud bolt assembly with dual heavy hex nuts',
  },
  {
    slug: 'sag-rods',
    path: '/products/sag-rods/',
    name: 'Sag Rods',
    shortDescription:
      'Threaded sag rods for PEB purlin bracing, structural steel, and solar racking cross-bracing.',
    classification: 'oem',
    image: '/images/products/threaded-rods/sag-rod.webp',
    imageAlt: 'KP Fasteners industrial sag rod assembly with dual hex nuts for PEB purlin bracing',
  },
  {
    slug: 'scaffold-accessories',
    path: '/products/scaffold-accessories/',
    name: 'Scaffold Accessories',
    shortDescription:
      'Scaffolding fastener accessories — manufactured and supplied, SKU-specific.',
    classification: 'ambiguous',
    image: '/images/products/threaded-rods/wedge-anchor.webp',
    imageAlt: 'Scaffold accessory — formwork hardware and wedge anchor accessories',
  },
  {
    slug: 'hex-bolts-nuts',
    path: '/products/hex-bolts-nuts/',
    name: 'Hex Bolts & Nuts',
    shortDescription:
      'Hex head bolts and hex nuts across metric and imperial standards — distribution range.',
    classification: 'trading',
    image: '/images/products/bolts/hex-bolt-hex-nut.webp',
    imageAlt: 'Hex bolt and hex nut — DIN 933 / DIN 934 distribution range',
  },
  {
    slug: 'csk-allen-bolts',
    path: '/products/csk-allen-bolts/',
    name: 'CSK Allen Bolts',
    shortDescription:
      'Countersunk socket-head cap screws — distribution range across grades and finishes.',
    classification: 'trading',
    image: '/images/products/bolts/allen-socket-csk-screw.webp',
    imageAlt: 'Countersunk Allen socket screw — DIN 7991 distribution range',
  },
  {
    slug: 'tie-rods',
    path: '/products/tie-rods/',
    name: 'Tie Rods',
    shortDescription:
      'Threaded tie rods and turnbuckle assemblies — distribution range.',
    classification: 'trading',
    image: '/images/products/threaded-rods/tie-rod.webp',
    imageAlt: 'Tie rod and formwork rod — D15 and D20 distribution range',
  },
  {
    slug: 'solar-accessories',
    path: '/products/solar-accessories/',
    name: 'Solar Accessories',
    shortDescription:
      'MMS bolts, T-head bolts, hanger bolts, module clamps — distribution range.',
    classification: 'trading',
    image: '/images/products/bolts/hex-flange-bolt.webp',
    imageAlt: 'Solar mounting accessory — hex flange bolt and mounting hardware',
  },
  {
    slug: 'custom-fasteners',
    path: '/products/custom-fasteners/',
    name: 'Custom Fasteners',
    shortDescription:
      'Drawing-based sourcing for non-standard fasteners — distribution / partner-supply.',
    classification: 'trading',
    image: '/images/products/bolts/socket-head-cap-screw.webp',
    imageAlt: 'Custom fasteners — socket-head cap screw and precision machined hardware',
  },
];

export function findProduct(slug: string): ProductCategory | undefined {
  return productCategories.find((p) => p.slug === slug);
}

export const RELATED_IMAGE_MAP: Record<string, { image: string; imageAlt: string }> = {
  '/products/foundation-bolts/': {
    image: '/images/products/bolts/foundation-anchor-bolts.webp',
    imageAlt: 'KP Fasteners foundation bolts — J, L, U and mechanical anchor bolts to IS 5624 and ASTM F1554',
  },
  '/products/stud-bolts/': {
    image: '/images/products/threaded-rods/threaded-rod-stud.webp',
    imageAlt: 'KP Fasteners ASTM A193 B7 stud bolt assembly with dual heavy hex nuts',
  },
  '/products/sag-rods/': {
    image: '/images/products/threaded-rods/sag-rod.webp',
    imageAlt: 'KP Fasteners industrial sag rod assembly with dual hex nuts for PEB purlin bracing',
  },
  '/products/scaffold-accessories/': {
    image: '/images/products/threaded-rods/wedge-anchor.webp',
    imageAlt: 'Scaffold accessory — formwork hardware and wedge anchor accessories',
  },
  '/products/hex-bolts-nuts/': {
    image: '/images/products/bolts/hex-bolt-hex-nut.webp',
    imageAlt: 'Hex bolt and hex nut — DIN 933 / DIN 934 distribution range',
  },
  '/products/csk-allen-bolts/': {
    image: '/images/products/bolts/allen-socket-csk-screw.webp',
    imageAlt: 'Countersunk Allen socket screw — DIN 7991 distribution range',
  },
  '/products/tie-rods/': {
    image: '/images/products/threaded-rods/tie-rod.webp',
    imageAlt: 'Tie rod and formwork rod — D15 and D20 distribution range',
  },
  '/products/solar-accessories/': {
    image: '/images/products/bolts/hex-flange-bolt.webp',
    imageAlt: 'Solar mounting accessory — hex flange bolt and mounting hardware',
  },
  '/products/custom-fasteners/': {
    image: '/images/products/bolts/socket-head-cap-screw.webp',
    imageAlt: 'Custom fasteners — socket-head cap screw and precision machined hardware',
  },
  '/materials/high-tensile-fasteners/': {
    image: '/product-images/high-tensile/hero.webp',
    imageAlt: 'High-tensile fasteners — property class 8.8 and 10.9 bolts',
  },
  '/materials/stainless-steel-fasteners/': {
    image: '/product-images/stainless-steel/hero.webp',
    imageAlt: 'KP Fasteners stainless steel 304 and 316 fastener range',
  },
  '/industries/construction-infrastructure/': {
    image: '/product-images/construction/hero.webp',
    imageAlt: 'Construction and infrastructure structural fasteners and PEB hardware',
  },
  '/industries/solar-mounting-fasteners/': {
    image: '/product-images/solar/hero.webp',
    imageAlt: 'Solar mounting structure fasteners and module clamps',
  },
  '/industries/automotive-heavy-engineering/': {
    image: '/product-images/automotive/hero.webp',
    imageAlt: 'Automotive and heavy engineering precision fasteners',
  },
};

export function getRelatedImage(href: string): { image: string; imageAlt: string } {
  const normalized = href.endsWith('/') ? href : `${href}/`;
  if (RELATED_IMAGE_MAP[normalized]) {
    return RELATED_IMAGE_MAP[normalized];
  }
  const matchedProd = productCategories.find((p) => p.path === normalized);
  if (matchedProd) {
    return { image: matchedProd.image, imageAlt: matchedProd.imageAlt };
  }
  return {
    image: '/images/products/bolts/hex-bolt-hex-nut.webp',
    imageAlt: 'KP Fasteners industrial hardware',
  };
}

